services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_pass
      POSTGRES_DB: products_db
    ports:
      - "5435:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: